INSERT INTO plantas (nombre, propiedades) VALUES 
('Ortiga', 'hierro, calcio, vitamina C y clorofila.'),
('Diente de león', 'diurético, depurativo y rico en antioxidantes.'),
('Cola de caballo', 'alto contenido en silicio, que fortalece cabello, piel y uñas.'),
('Stevia', 'edulcorante natural y propiedades antioxidantes.'),
('Malva', 'antiinflamatoria y calmante para el sistema respiratorio.'),
('Perilla', 'antioxidantes y antiinflamatorias.'),
('Helicrisium italicum', 'antiinflamatorias y cicatrizantes.'),
('Llantén', 'expectorantes y antiinflamatorias.'),
('Tomillo', 'antibacterianas y es bueno para el sistema respiratorio.'),
('Melisa', 'calmantes y digestivas.'),
('Hierba luisa', 'digestivas y calmantes.'),
('Menta', 'refrescante y ayuda a aliviar problemas digestivos.'),
('Salvia', 'antibacterianas y antioxidantes.'),
('Té de roca', 'digestivo y ayuda en problemas gastrointestinales.'),
('Santolina', 'antiinflamatoria y se usa en problemas digestivos.'),
('Maravilla', 'cicatrizantes y antiinflamatorias.'),
('Anís verde', 'digestivo y carminativo.'),
('Romero', 'estimulantes y antioxidantes.'),
('Hipérico', 'antidepresivas y cicatrizantes.'),
('Milramas', 'cicatrizantes y astringentes.'),
('Bolsa de pastor', 'hemostáticas.'),
('Perilla', 'antioxidantes y antiinflamatorias.'),
('Flor de sauce', 'antiinflamatorias y analgésicas.'),
('Espino blanco', 'cardiotónicas.'),
('Lavanda', 'relajante y ayuda a calmar la ansiedad.'),
('Nepetia cataria', 'calmante y se usa para problemas digestivos.'),
('Romero', 'estimulantes y antioxidantes.'),
('Anís verde', 'digestivo y carminativo.');
('Malvavisco', 'calmante y ayuda a aliviar irritaciones en la garganta y el tracto digestivo.'),
('Hoja de nogal', 'antiparasitarias,antiinflamatorias y antioxidantes') 